baseURL = "/"
languageCode = "ja"
title = "Art Gallery"

theme = ["gallerydeluxe"]

[params]
  description = "Gallery Deluxe ベースのアートギャラリー"
  [params.gallerydeluxe]
    shuffle = false
    reverse = false
    enable_exif = false

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.imports]]
    path = "github.com/bep/gallerydeluxe"
